#!/bin/sh

case "$1" in
	start)
		echo "Starting MiSTer"
		start-stop-daemon -S -b -q -m -p /var/run/mister.pid -x /bin/nice -n -19 /media/fat/MiSTer
		exit $?
		;;

	stop)
		echo "Stopping MiSTer"
		start-stop-daemon -K -q -p /var/run/mister.pid 2>/dev/null
		exit $?
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
