#!/bin/sh

case "$1" in
	start)
		echo "Starting SPI"
	        /sbin/modprobe spidev
			# This is actually spidev0.0,
			# which is automatically created
			# but we alias it to this one too 
			# to make it consistent with the Allwinner D1
	        /bin/mknod /dev/spidev1.0 c 153 0
		exit $?
		;;

	stop)
		echo "Stopping SPI"
		/sbin/rmmod spidev
		exit $?
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
