MYOPENFPGALOADER_VERSION = 0.11.0
MYOPENFPGALOADER_SOURCE = v$(MYOPENFPGALOADER_VERSION).tar.gz
MYOPENFPGALOADER_SITE = https://github.com/MiSTeX-devel/openFPGALoader/archive/refs/tags
MYOPENFPGALOADER_SITE_METHOD = wget
MYOPENFPGALOADER_INSTALL_STAGING = YES
MYOPENFPGALOADER_LICENSE = Apache-2.0
MYOPENFPGALOADER_LICENSE_FILES = LICENSE
MYOPENFPGALOADER_CPE_ID_VENDOR = trabucayre
MYOPENFPGALOADER_DEPENDENCIES = libftdi1 zlib
MY_CXX = $(subst g++,cpp,$(TARGET_CXX))
MYOPENFPGALOADER_CONF_OPTS += -DCMAKE_C_COMPILER=$(TARGET_CC) -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"

ifeq ($(BR2_PACKAGE_HAS_UDEV),y)
MYOPENFPGALOADER_DEPENDENCIES += udev
MYOPENFPGALOADER_CONF_OPTS += -DENABLE_UDEV=ON
else
MYOPENFPGALOADER_CONF_OPTS += -DENABLE_UDEV=OFF
endif

$(eval $(cmake-package))