MYOPENFPGALOADER_VERSION = 0.11.0
MYOPENFPGALOADER_SOURCE = v$(MYOPENFPGALOADER_VERSION).tar.gz
MYOPENFPGALOADER_SITE = https://github.com/MiSTeX-devel/openFPGALoader/archive/refs/tags
MYOPENFPGALOADER_SITE_METHOD = wget
MYOPENFPGALOADER_INSTALL_STAGING = YES
MYOPENFPGALOADER_LICENSE = Apache-2.0
MYOPENFPGALOADER_LICENSE_FILES = LICENSE
MYOPENFPGALOADER_CPE_ID_VENDOR = trabucayre
MYOPENFPGALOADER_DEPENDENCIES = libftdi1 zlib
MY_CXX = $(subst g++,cpp,$(TARGET_CXX))
MYOPENFPGALOADER_CONF_OPTS += -DCMAKE_C_COMPILER=$(TARGET_CC) -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
#MYOPENFPGALOADER_MAKE_OPTS += CXXFLAGS="$(TARGET_CFLAGS) -D__riscv_xlen=64 -D__riscv_flen=64 -D__riscv_float_abi_double=1 -D__riscv_atomic=1 -wrdlbrmfd $(HOSTCC)"
MYOPENFPGALOADER_MAKE_OPTS += VERBOSE=1



# we are built before ccache
#HOST_MYOPENFPGALOADER_CONF_ENV = \
#	CC="$(HOSTCC_NOCCACHE)" \
#	CXX="$(HOSTCXX_NOCCACHE)"

ifeq ($(BR2_PACKAGE_HAS_UDEV),y)
MYOPENFPGALOADER_DEPENDENCIES += udev
MYOPENFPGALOADER_CONF_OPTS += -DENABLE_UDEV=ON
else
MYOPENFPGALOADER_CONF_OPTS += -DENABLE_UDEV=OFF
endif

$(eval $(cmake-package))