#!/bin/sh

case "$1" in
	start)
		echo "Mounting /media/fat"
		mkdir -p /media/fat
		/bin/mount /dev/mmcblk0p3 /media/fat
		exit $?
		;;

	stop)
		echo "Unmounting /media/fat"
		/bin/umount /media/fat
		exit $?
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
